name: Deploy FileUp

on:
  push:
    branches:
      - main

jobs:
  deploy:
    if: startsWith(github.event.head_commit.message, '[deploy]')
    runs-on: ubuntu-latest

    steps:
      - run: echo "Host=${{ secrets.VPS_HOST }} User=${{ secrets.VPS_USER }}"

      - name: Deploy on VPS via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}   # e.g. kali
          key: ${{ secrets.VPS_PRIVATE_KEY }} # same one as other projects
          script: |
            cd /var/www/upload/FileUp
            git reset --hard
            git pull origin main
            dotnet publish -c Release -o /var/www/upload/published
            sudo systemctl restart fileup
